GMSH::Gmsh Class Reference
#include <gmsh_read.h>
Public Member Functions
Gmsh ()=default
Gmsh (const std::string &filename, bool verbose=false)
Gmsh (const Gmsh &)=delete
No copy.
Gmsh (Gmsh &&)=delete
No move.
Gmsh & operator= (Gmsh &&)=delete
No move assignment.
~Gmsh ()=default
Destructor.
const std::vector< Node > & getNodes () const
Getters.
virtual Node & getNode (size_t n)
const std::vector< Edge > & getEdges () const
Edge & getEdge (size_t e)
const std::vector< Quad > & getQuads () const
Quad & getQuad (size_t q)
const std::vector< Hexa > & getHexas () const
Hexa & getHexa (size_t h)
unsigned getBoundSize () const
Getters.
unsigned getNodesSize () const
unsigned getEdgesSize () const
unsigned getQuadsSize () const
unsigned getHexasSize () const
unsigned getMeshDim () const
int getNodesPerElement () const
int getEdgesPerElement () const
int getFacesPerElement () const
void printInfo (bool)
: INFO
void nodesInfo ()
void edgesInfo ()
void quadsInfo ()
void hexasInfo ()
int getBoundaryId (const std::string &bName)
Static Public Member Functions
static std::vector< Quad > getFaces (const Hexa &hexa)
get faces form current hexa.
Public Attributes
std::vector< Boundary > boundaries
std::unordered_map< int, int > orderedBC
Private Types
enum ElementType {
Vertex_ = 15
, Line_ = 1
, Quadrilateral_ = 3
, Hexahedral_ = 5
,
Line2ndOrder_ = 8
, Quadrilateral2ndOrder_ = 10
, Hexahedral2ndOrder_ = 12
 }
Element types.
enum EntityType { Point_ = 0
, Curve_ = 1
, Surface_ = 2
, Volume_ = 3
 }
Private Member Functions
void collectNodes ()
: collect nodes
bool collectEdges ()
: collect the edges into a vector of nodes tags
bool collectQuads ()
: collect quadrilateral elements into vector of tags and ids
bool collectHexas ()
: collect hexahedrals elements into vector of tags and ids
void addMissingEdge (Quad &quad)
void addMissingQuad (Hexa &hex)
void kernel ()
void fillInTags (Hexa &hexa)
void fillInTags (Quad &quad)
void addInternalEdge (std::vector< int > &line)
void addInternalQuad (std::vector< int > &face)
void renumber ()
void entityTagToBoundaries ()
: get the dimension and the tag of the boundary
void renumberBCondition ()
renumberBCondition the boundaries. Gmsh gives the user the flexibility to choose the numbering, however oomph-lib require the numbering starting from 0.
bool correctOrientation (Quad &quad)
Check the orientation.
bool correctOrientation (const Hexa &hex)
Check the orientation.
std::vector< double > getCenter (const Hexa &hex)
std::vector< double > getCenter (const std::vector< int > &nodesTag)
std::vector< double > getArea (const std::vector< int > &points)
Static Private Member Functions
static bool inList (std::vector< int > &q, std::vector< Edge > &E)
Utilities.
static bool inList (std::vector< int > &q, std::vector< Quad > &Q)
static bool areSimilar (std::vector< int > a, std::vector< int > b)
static std::vector< Edge > getEdges (const Quad &quad)
Private Attributes
bool verbose_ = false
std::ifstream mshFile
int minNodeTag = 0
std::vector< bool > found4
std::vector< bool > found2
std::vector< bool > found20
std::vector< Point > pEntities
Entities.
std::vector< Curve > cEntities
std::vector< Surface > sEntities
std::vector< Volume > vEntities
std::vector< Vertex > vertices
Vertex, and Elements.
std::vector< Element > elements
std::vector< Node > nodes
std::vector< Edge > edges
std::vector< Quad > quads
std::vector< Hexa > hexas
std::vector< Quad > quadList
std::vector< Edge > edgeList
std::vector< std::vector< int > > fourNodesList
std::vector< std::vector< int > > commonInternalEdges
std::vector< std::vector< int > > twoNodesList
std::vector< std::vector< int > > internalQuads
int nodesPerElement = defFlag
int edgesPerElement = defFlag
int facesPerElement = defFlag
std::vector< Tuple > tuples
std::vector< int > oldNumber
std::chrono::duration< double > duration {}
Detailed Description
Definition at line 278 of file gmsh_read.h.
Member Enumeration Documentation
ElementType
enum GMSH::Gmsh::ElementType [private]
Element types.
Enumerator
Vertex_
Line_
Quadrilateral_
Hexahedral_
Line2ndOrder_
Quadrilateral2ndOrder_
Hexahedral2ndOrder_
Definition at line 440 of file gmsh_read.h.
EntityType
enum GMSH::Gmsh::EntityType [private]
Enumerator
Point_
Curve_
Surface_
Volume_
Definition at line 451 of file gmsh_read.h.
Constructor & Destructor Documentation
Gmsh() [1/4]
GMSH::Gmsh::Gmsh () [default]
Gmsh() [2/4]
GMSH::Gmsh::Gmsh (const std::string & filename, bool verbose = false) [explicit]
Constructor point Entities
curve Entities
Surface Entities
Volume Entities
Section of collecting already complete elements
renumbering B.C. section
Definition at line 16 of file gmsh_read.cc.
References boundaries, cEntities, collectNodes(), GMSH::Curve::curveTag, GMSH::Surface::curveTags, GMSH::defFlag, GMSH::Boundary::dim, duration, elements, entityTagToBoundaries(), Hexahedral2ndOrder_, Hexahedral_, i, kernel(), Line2ndOrder_, Line_, minNodeTag, mshFile, nodes, GMSH::Surface::numBoundingCurves, GMSH::Curve::numBoundingPoints, GMSH::Volume::numBoundingSurfaces, GMSH::Point::numPhysicalTags, GMSH::Curve::numPhysicalTags, GMSH::Surface::numPhysicalTags, GMSH::Volume::numPhysicalTags, pEntities, GMSH::Boundary::physicalNames, GMSH::Point::physicalTags, GMSH::Curve::physicalTags, GMSH::Surface::physicalTags, GMSH::Volume::physicalTags, GMSH::Point::pointTag, GMSH::Curve::pointTags, printInfo(), Quadrilateral2ndOrder_, Quadrilateral_, renumber(), renumberBCondition(), sEntities, GMSH::Surface::surfaceTag, GMSH::Volume::surfaceTags, GMSH::Boundary::tag, vEntities, verbose_, Vertex_, vertices, GMSH::Volume::volumeTag, GMSH::Point::x, GMSH::Point::y, and GMSH::Point::z.
Gmsh() [3/4]
GMSH::Gmsh::Gmsh (const Gmsh &) [delete]
No copy.
Gmsh() [4/4]
GMSH::Gmsh::Gmsh (Gmsh &&) [delete]
No move.
~Gmsh()
GMSH::Gmsh::~Gmsh () [default]
Destructor.
Member Function Documentation
addInternalEdge()
void GMSH::Gmsh::addInternalEdge (std::vector< int > & line) [private]
Definition at line 847 of file gmsh_read.cc.
References e, GMSH::Edge::edgeTag, and GMSH::Edge::nodesTag.
addInternalQuad()
void GMSH::Gmsh::addInternalQuad (std::vector< int > & face) [private]
Definition at line 858 of file gmsh_read.cc.
References GMSH::Quad::nodesTag, and GMSH::Quad::quadTag.
addMissingEdge()
void GMSH::Gmsh::addMissingEdge (Quad & quad) [private]
Definition at line 738 of file gmsh_read.cc.
addMissingQuad()
void GMSH::Gmsh::addMissingQuad (Hexa & hex) [private]
Definition at line 725 of file gmsh_read.cc.
areSimilar()
bool GMSH::Gmsh::areSimilar (std::vector< int > a, std::vector< int > b) [static], [private]
Function to check vectors of the same length if they are similar.
Parameters
 in a
 in b
 out boolean
Definition at line 873 of file gmsh_read.cc.
collectEdges()
bool GMSH::Gmsh::collectEdges () [private]
: collect the edges into a vector of nodes tags
Fill in [edges] vector
Definition at line 581 of file gmsh_read.cc.
collectHexas()
bool GMSH::Gmsh::collectHexas () [private]
: collect hexahedrals elements into vector of tags and ids
Fill in [hexas] vector
Definition at line 678 of file gmsh_read.cc.
References GMSH::Hexa::boundaries, GMSH::defFlag, GMSH::Hexa::entityDim, GMSH::Hexa::entityTag, GMSH::Hexa::hexaTag, and GMSH::Hexa::nodesTag.
collectNodes()
void GMSH::Gmsh::collectNodes () [private]
: collect nodes
Fill in [nodes] vector
Definition at line 458 of file gmsh_read.cc.
References GMSH::defFlag.
Referenced by Gmsh().
collectQuads()
bool GMSH::Gmsh::collectQuads () [private]
: collect quadrilateral elements into vector of tags and ids
Fill in [quads] vector
Definition at line 628 of file gmsh_read.cc.
References GMSH::Quad::boundaries, GMSH::defFlag, GMSH::Quad::entityDim, GMSH::Quad::entityTag, GMSH::Quad::nodesTag, and GMSH::Quad::quadTag.
correctOrientation() [1/2]
bool GMSH::Gmsh::correctOrientation (const Hexa & hex) [private]
Check the orientation.
Definition at line 913 of file gmsh_read.cc.
correctOrientation() [2/2]
bool GMSH::Gmsh::correctOrientation (Quad & quad) [private]
Check the orientation.
Definition at line 880 of file gmsh_read.cc.
References i, GMSH::Quad::nodesTag, and GMSH::Quad::quadTag.
edgesInfo()
void GMSH::Gmsh::edgesInfo ()
Definition at line 1238 of file gmsh_read.cc.
References i.
entityTagToBoundaries()
void GMSH::Gmsh::entityTagToBoundaries () [private]
: get the dimension and the tag of the boundary
Parameters
 in boundary
 out DimsAndTags
Get boundaries from entities.
Definition at line 385 of file gmsh_read.cc.
References GMSH::Tuple::boundary, GMSH::Tuple::entityTag, and GMSH::Tuple::EntityType.
Referenced by Gmsh().
fillInTags() [1/2]
void GMSH::Gmsh::fillInTags (Hexa & hexa) [private]
Filling QUADS tags for hexas
filling edges tags for quads
Filling edges tags for hexas
Definition at line 1066 of file gmsh_read.cc.
References GMSH::Hexa::edgesTag, i, and GMSH::Hexa::quadsTag.
fillInTags() [2/2]
void GMSH::Gmsh::fillInTags (Quad & quad) [private]
filling edges tags for quads
Definition at line 1125 of file gmsh_read.cc.
References GMSH::Quad::edgesTag.
getArea()
std::vector< double > GMSH::Gmsh::getArea (const std::vector< int > & points) [private]
Definition at line 1033 of file gmsh_read.cc.
getBoundaryId()
int GMSH::Gmsh::getBoundaryId (const std::string & bName)
getBoundSize()
unsigned GMSH::Gmsh::getBoundSize () const
Getters.
Definition at line 1152 of file gmsh_read.cc.
getCenter() [1/2]
std::vector< double > GMSH::Gmsh::getCenter (const Hexa & hex) [private]
Definition at line 996 of file gmsh_read.cc.
References GMSH::Hexa::hexaTag, GMSH::Hexa::nodesTag, GMSH::small, and GMSH::vSmall.
getCenter() [2/2]
std::vector< double > GMSH::Gmsh::getCenter (const std::vector< int > & nodesTag) [private]
Definition at line 988 of file gmsh_read.cc.
getEdge()
Edge & GMSH::Gmsh::getEdge (size_t e) [inline]
Definition at line 301 of file gmsh_read.h.
References e, and edges.
getEdges() [1/2]
const std::vector< GMSH::Edge > & GMSH::Gmsh::getEdges () const
Definition at line 1146 of file gmsh_read.cc.
getEdges() [2/2]
std::vector< GMSH::Edge > GMSH::Gmsh::getEdges (const Quad & quad) [static], [private]
Definition at line 964 of file gmsh_read.cc.
References GMSH::Quad::nodesTag.
getEdgesPerElement()
int GMSH::Gmsh::getEdgesPerElement () const
Definition at line 1175 of file gmsh_read.cc.
getEdgesSize()
unsigned GMSH::Gmsh::getEdgesSize () const
Definition at line 1156 of file gmsh_read.cc.
getFaces()
std::vector< GMSH::Quad > GMSH::Gmsh::getFaces (const Hexa & hexa) [static]
get faces form current hexa.
Definition at line 953 of file gmsh_read.cc.
References GMSH::Hexa::nodesTag.
getFacesPerElement()
int GMSH::Gmsh::getFacesPerElement () const
Definition at line 1177 of file gmsh_read.cc.
getHexa()
Hexa & GMSH::Gmsh::getHexa (size_t h) [inline]
Definition at line 307 of file gmsh_read.h.
References hexas.
getHexas()
const std::vector< GMSH::Hexa > & GMSH::Gmsh::getHexas () const
Definition at line 1150 of file gmsh_read.cc.
getHexasSize()
unsigned GMSH::Gmsh::getHexasSize () const
Definition at line 1160 of file gmsh_read.cc.
getMeshDim()
unsigned GMSH::Gmsh::getMeshDim () const
Definition at line 1162 of file gmsh_read.cc.
getNode()
virtual Node & GMSH::Gmsh::getNode (size_t n) [inline], [virtual]
Definition at line 298 of file gmsh_read.h.
References nodes.
getNodes()
const std::vector< GMSH::Node > & GMSH::Gmsh::getNodes () const
Getters.
Definition at line 1144 of file gmsh_read.cc.
getNodesPerElement()
int GMSH::Gmsh::getNodesPerElement () const
Definition at line 1173 of file gmsh_read.cc.
getNodesSize()
unsigned GMSH::Gmsh::getNodesSize () const
Definition at line 1154 of file gmsh_read.cc.
getQuad()
Quad & GMSH::Gmsh::getQuad (size_t q) [inline]
Definition at line 304 of file gmsh_read.h.
References quads.
getQuads()
const std::vector< GMSH::Quad > & GMSH::Gmsh::getQuads () const
Definition at line 1148 of file gmsh_read.cc.
getQuadsSize()
unsigned GMSH::Gmsh::getQuadsSize () const
Definition at line 1158 of file gmsh_read.cc.
hexasInfo()
void GMSH::Gmsh::hexasInfo ()
Definition at line 1293 of file gmsh_read.cc.
References i.
inList() [1/2]
bool GMSH::Gmsh::inList (std::vector< int > & q, std::vector< Edge > & E) [static], [private]
Utilities.
Definition at line 1337 of file gmsh_read.cc.
References e.
inList() [2/2]
bool GMSH::Gmsh::inList (std::vector< int > & q, std::vector< Quad > & Q) [static], [private]
Definition at line 1346 of file gmsh_read.cc.
kernel()
void GMSH::Gmsh::kernel () [private]
Fill in internals based on the element type. Gmsh always put the highest element type last in order.
Fill in Tags
Attempt to reorder hexas nodes and add missing quads/faces and edges
Definition at line 485 of file gmsh_read.cc.
References GMSH::Hexa::hexaTag, and GMSH::Hexa::nodesTag.
Referenced by Gmsh().
nodesInfo()
void GMSH::Gmsh::nodesInfo ()
Definition at line 1207 of file gmsh_read.cc.
References i.
operator=()
Gmsh & GMSH::Gmsh::operator= (Gmsh &&) [delete]
No move assignment.
printInfo()
void GMSH::Gmsh::printInfo (bool info = false)
: INFO
Definition at line 1180 of file gmsh_read.cc.
References i.
Referenced by Gmsh().
quadsInfo()
void GMSH::Gmsh::quadsInfo ()
Definition at line 1263 of file gmsh_read.cc.
References i.
renumber()
void GMSH::Gmsh::renumber () [private]
Definition at line 747 of file gmsh_read.cc.
References GMSH::defFlag.
Referenced by Gmsh().
renumberBCondition()
void GMSH::Gmsh::renumberBCondition () [private]
renumberBCondition the boundaries. Gmsh gives the user the flexibility to choose the numbering, however oomph-lib require the numbering starting from 0.
Definition at line 444 of file gmsh_read.cc.
References i.
Referenced by Gmsh().
Member Data Documentation
boundaries
std::vector<Boundary> GMSH::Gmsh::boundaries
Definition at line 343 of file gmsh_read.h.
Referenced by Gmsh().
cEntities
std::vector<Curve> GMSH::Gmsh::cEntities [private]
Definition at line 415 of file gmsh_read.h.
Referenced by Gmsh().
commonInternalEdges
std::vector<std::vector<int> > GMSH::Gmsh::commonInternalEdges [private]
Definition at line 435 of file gmsh_read.h.
duration
std::chrono::duration<double> GMSH::Gmsh::duration {} [private]
Definition at line 470 of file gmsh_read.h.
Referenced by Gmsh().
edgeList
std::vector<Edge> GMSH::Gmsh::edgeList [private]
Definition at line 431 of file gmsh_read.h.
edges
std::vector<Edge> GMSH::Gmsh::edges [private]
Definition at line 427 of file gmsh_read.h.
Referenced by getEdge().
edgesPerElement
int GMSH::Gmsh::edgesPerElement = defFlag [private]
Definition at line 460 of file gmsh_read.h.
elements
std::vector<Element> GMSH::Gmsh::elements [private]
Definition at line 423 of file gmsh_read.h.
Referenced by Gmsh().
facesPerElement
int GMSH::Gmsh::facesPerElement = defFlag [private]
Definition at line 462 of file gmsh_read.h.
found2
std::vector<bool> GMSH::Gmsh::found2 [private]
Definition at line 410 of file gmsh_read.h.
found20
std::vector<bool> GMSH::Gmsh::found20 [private]
Definition at line 411 of file gmsh_read.h.
found4
std::vector<bool> GMSH::Gmsh::found4 [private]
Definition at line 409 of file gmsh_read.h.
fourNodesList
std::vector<std::vector<int> > GMSH::Gmsh::fourNodesList [private]
Definition at line 434 of file gmsh_read.h.
hexas
std::vector<Hexa> GMSH::Gmsh::hexas [private]
Definition at line 429 of file gmsh_read.h.
Referenced by getHexa().
internalQuads
std::vector<std::vector<int> > GMSH::Gmsh::internalQuads [private]
Definition at line 437 of file gmsh_read.h.
minNodeTag
int GMSH::Gmsh::minNodeTag = 0 [private]
Definition at line 408 of file gmsh_read.h.
Referenced by Gmsh().
mshFile
std::ifstream GMSH::Gmsh::mshFile [private]
Definition at line 407 of file gmsh_read.h.
Referenced by Gmsh().
nodes
std::vector<Node> GMSH::Gmsh::nodes [private]
Definition at line 426 of file gmsh_read.h.
Referenced by getNode(), and Gmsh().
nodesPerElement
int GMSH::Gmsh::nodesPerElement = defFlag [private]
Definition at line 458 of file gmsh_read.h.
oldNumber
std::vector<int> GMSH::Gmsh::oldNumber [private]
Definition at line 467 of file gmsh_read.h.
orderedBC
std::unordered_map<int, int> GMSH::Gmsh::orderedBC
Definition at line 345 of file gmsh_read.h.
pEntities
std::vector<Point> GMSH::Gmsh::pEntities [private]
Entities.
Definition at line 414 of file gmsh_read.h.
Referenced by Gmsh().
quadList
std::vector<Quad> GMSH::Gmsh::quadList [private]
Definition at line 430 of file gmsh_read.h.
quads
std::vector<Quad> GMSH::Gmsh::quads [private]
Definition at line 428 of file gmsh_read.h.
Referenced by getQuad().
sEntities
std::vector<Surface> GMSH::Gmsh::sEntities [private]
Definition at line 416 of file gmsh_read.h.
Referenced by Gmsh().
tuples
std::vector<Tuple> GMSH::Gmsh::tuples [private]
Definition at line 465 of file gmsh_read.h.
twoNodesList
std::vector<std::vector<int> > GMSH::Gmsh::twoNodesList [private]
Definition at line 436 of file gmsh_read.h.
vEntities
std::vector<Volume> GMSH::Gmsh::vEntities [private]
Definition at line 417 of file gmsh_read.h.
Referenced by Gmsh().
verbose_
bool GMSH::Gmsh::verbose_ = false [private]
Definition at line 405 of file gmsh_read.h.
Referenced by Gmsh().
vertices
std::vector<Vertex> GMSH::Gmsh::vertices [private]
Vertex, and Elements.
Definition at line 422 of file gmsh_read.h.
Referenced by Gmsh().
The documentation for this class was generated from the following files:
gmsh_read.h
gmsh_read.cc